import { Blog } from "@/components/blogs/Blog";
import { ALL_BLOGS } from "@/utils/utils";
import Head from "next/head";
import styles from "../styles/Blogs.module.css";

export default function Blogs() {
  return (
    <div className={styles.blogs}>
      <Head>
        <title>RR | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Our Blogs</h2>

      <div className={styles.allBlogs}>
        {ALL_BLOGS.map((blog) => {
          return (
            <Blog title={blog.title} author={blog.author} image={blog.image} />
          );
        })}
      </div>
    </div>
  );
}
