import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Hero } from "@/components/home/Hero";
import { WhoAreTheRegenRangers } from "@/components/home/WhoAreTheRegenRangers";
import { SafeGuardingWeb3 } from "@/components/home/SafeGuardingWeb3";
import { About } from "@/components/home/About";
import { Sponsors } from "@/components/home/Sponsors";

export default function Home() {
  return (
    <>
      <Head>
        <title>RR | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />

        <WhoAreTheRegenRangers />

        <About />

        <SafeGuardingWeb3 />

        <Sponsors />
      </main>
    </>
  );
}
